require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/import_errors", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ImportError. As you add validations to ImportError, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ImportErrorsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      ImportError.create! valid_attributes
      get import_errors_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      import_error = ImportError.create! valid_attributes
      get import_error_url(import_error), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ImportError" do
        expect {
          post import_errors_url,
               params: { import_error: valid_attributes }, headers: valid_headers, as: :json
        }.to change(ImportError, :count).by(1)
      end

      it "renders a JSON response with the new import_error" do
        post import_errors_url,
             params: { import_error: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ImportError" do
        expect {
          post import_errors_url,
               params: { import_error: invalid_attributes }, as: :json
        }.to change(ImportError, :count).by(0)
      end

      it "renders a JSON response with errors for the new import_error" do
        post import_errors_url,
             params: { import_error: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested import_error" do
        import_error = ImportError.create! valid_attributes
        patch import_error_url(import_error),
              params: { import_error: new_attributes }, headers: valid_headers, as: :json
        import_error.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the import_error" do
        import_error = ImportError.create! valid_attributes
        patch import_error_url(import_error),
              params: { import_error: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the import_error" do
        import_error = ImportError.create! valid_attributes
        patch import_error_url(import_error),
              params: { import_error: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested import_error" do
      import_error = ImportError.create! valid_attributes
      expect {
        delete import_error_url(import_error), headers: valid_headers, as: :json
      }.to change(ImportError, :count).by(-1)
    end
  end
end
